import streamlit as st
import time
from frontend.components.api_client import api


def render_assessments_view():
    st.markdown("### 📝 Personalized AI Placement Assessment")
    st.markdown(
        "Assessments are **100% dynamically generated by Azure AI Foundry** (`PlacementPreparationAgent:4`) "
        "tailored specifically to your **Resume**, **Target Job Description**, and **Assessment History**. "
        "**Zero predefined questions.** Scoring is deterministic, followed by deep AI diagnostic performance analysis."
    )
    st.markdown("<span class='credit-pill'>⚡ Pure Azure AI Foundry — Zero Predefined Questions</span>", unsafe_allow_html=True)

    # Fetch user profile, resume, and JD info from backend source of truth
    profile = {}
    resume = None
    job = None
    try:
        profile = api.get_profile() or {}
    except Exception as e:
        st.warning(f"Could not load candidate profile: {e}")

    try:
        resume = api.get_latest_resume()
    except Exception:
        resume = None

    # Use backend unified profile response if direct resume lookup returned None
    if not resume and profile.get("active_resume"):
        resume = profile.get("active_resume")

    try:
        job = api.get_latest_job()
    except Exception:
        job = None

    if not job and profile.get("active_job"):
        job = profile.get("active_job")

    default_role = profile.get("target_role") or "Backend Engineer"

    # Requirement 7: Distinguish RESUME EXISTS from RESUME AI ANALYSIS EXISTS
    has_resume = (
        resume is not None
        and (
            bool(resume.get("has_content"))
            or bool(resume.get("raw_text"))
            or bool(resume.get("id"))
            or bool(resume.get("filename"))
        )
    )
    has_resume_intelligence = bool(resume and (resume.get("has_intelligence") or resume.get("parsed_data")))

    has_job = (
        job is not None
        and (
            bool(job.get("has_content"))
            or bool(job.get("raw_text"))
            or bool(job.get("id"))
            or bool(job.get("title"))
        )
    )
    has_job_intelligence = bool(job and (job.get("has_intelligence") or job.get("parsed_data")))

    tabs = st.tabs(["📝 Current Assessment", "✨ Generate New Assessment", "📜 Assessment History"])

    # -------------------------------------------------------------
    # TAB 1: CURRENT ASSESSMENT (MCQ Form or Completed Results)
    # -------------------------------------------------------------
    with tabs[0]:
        try:
            assessments = api.list_assessments()
        except Exception as e:
            st.error(f"Failed to load assessments: {str(e)}")
            return

        if not assessments:
            st.info("No personalized assessments currently generated. Go to the **✨ Generate New Assessment** tab to create one.")
        else:
            assessment_titles = {
                a["id"]: f"{a['title']} ({a.get('role') or 'Role'} - {a.get('difficulty', 'Intermediate')} - {a.get('status', 'pending').upper()})"
                for a in assessments
            }

            default_index = 0
            if "active_assessment_id" in st.session_state and st.session_state["active_assessment_id"] in assessment_titles:
                default_index = list(assessment_titles.keys()).index(st.session_state["active_assessment_id"])

            selected_id = st.selectbox(
                "Select Assessment to Take or Review",
                options=list(assessment_titles.keys()),
                index=default_index,
                format_func=lambda x: assessment_titles[x]
            )

            assessment = next((a for a in assessments if a["id"] == selected_id), None)
            if assessment:
                st.markdown(f"#### 🎯 {assessment.get('title')}")
                st.caption(
                    f"Role Focus: **{assessment.get('role')}** | "
                    f"Difficulty: **{assessment.get('difficulty')}** | "
                    f"Questions: **{assessment.get('total_questions')}** | "
                    f"Status: **{assessment.get('status', 'pending').upper()}**"
                )

                # Check if assessment is already completed or has stored result in DB (Requirement 30)
                stored_result = None
                try:
                    stored_result = api.get_assessment_result(selected_id)
                except Exception:
                    pass

                # If completed or result exists in DB, display the comprehensive result analysis
                if stored_result:
                    _display_assessment_result(stored_result)
                else:
                    # Render MCQ Assessment Form
                    _render_mcq_form(selected_id, assessment)

    # -------------------------------------------------------------
    # TAB 2: GENERATE NEW PERSONALIZED ASSESSMENT
    # -------------------------------------------------------------
    with tabs[1]:
        st.markdown("#### ✨ Generate a Fresh Personalized Assessment")
        st.write(
            "Every question is freshly generated by Azure AI Foundry based on your background and target JD. "
            "No static question bank is used."
        )

        col_stat1, col_stat2 = st.columns(2)
        with col_stat1:
            if has_resume:
                fname = resume.get("filename", "Resume")
                ver = f" (v{resume.get('version')})" if resume.get("version") else ""
                if has_resume_intelligence:
                    st.success(f"✅ Active Resume: `{fname}`{ver} — Intelligence Extracted")
                else:
                    st.info(f"ℹ️ Active Resume: `{fname}`{ver} — Ready (Analyze in 'Resume Upload' for deeper intelligence)")
            else:
                st.error("⚠️ Resume missing! Please upload your resume in the '📄 Resume / CV Upload' view.")
        with col_stat2:
            if has_job:
                jtitle = job.get("title", "Job Description")
                if has_job_intelligence:
                    st.success(f"✅ Job Description Linked: `{jtitle}` — Requirements Extracted")
                else:
                    st.info(f"ℹ️ Job Description Linked: `{jtitle}` — Ready for assessment")
            else:
                st.error("⚠️ Job Description missing! Please link a job in the '🎯 Target Job Description' view.")

        target_role_input = st.text_input(
            "Target Role",
            value=default_role,
            help="The job role you are preparing for."
        )

        num_q_options = [5, 10, 15, 20]
        num_q = st.select_slider(
            "Number of Assessment Questions (Dynamic)",
            options=num_q_options,
            value=5,
            help="Select how many questions Azure AI Foundry should dynamically generate."
        )

        can_generate = has_resume and has_job

        if not can_generate:
            st.warning("⚠️ Both your Resume and Target Job Description must be uploaded before generating a personalized assessment.")

        if st.button("🚀 Generate Personalized Assessment via Azure AI Foundry", type="primary", use_container_width=True, disabled=not can_generate):
            # Real Status Progression (Requirement 29)
            status_container = st.status("Initializing AI generation pipeline...", expanded=True)
            try:
                status_container.write("🔍 Analyzing your resume and project experience...")
                time.sleep(0.4)
                status_container.write("📋 Extracting target job description requirements & responsibilities...")
                time.sleep(0.4)
                status_container.write("🧩 Identifying candidate-vs-JD skill gaps and evaluating assessment history...")
                time.sleep(0.4)
                status_container.write(f"🤖 Invoking Azure AI Foundry (`PlacementPreparationAgent:4`) for {num_q} personalized MCQs...")

                new_assessment = api.generate_personalized_assessment(
                    role=target_role_input,
                    num_questions=num_q
                )

                status_container.write("✅ Validating question schemas, options integrity, and technical relevance...")
                time.sleep(0.3)
                status_container.write("💾 Storing generated questions in the database...")
                time.sleep(0.3)
                status_container.update(label="Assessment Generation Complete!", state="complete", expanded=False)

                st.success(f"Successfully generated: {new_assessment.get('title')}")
                st.session_state["active_assessment_id"] = new_assessment.get("id")
                st.rerun()

            except Exception as e:
                status_container.update(label="Generation Failed", state="error", expanded=True)
                st.error(f"Unable to generate your personalized assessment right now. {str(e)}")

    # -------------------------------------------------------------
    # TAB 3: ASSESSMENT HISTORY
    # -------------------------------------------------------------
    with tabs[2]:
        st.markdown("#### 📜 Candidate Assessment History")
        st.write("Track your scores, strengths, skill gaps, and improvement plans across all past evaluations.")
        try:
            history = api.get_assessment_history()
            if not history:
                st.info("No assessments completed yet. Complete an assessment to see your diagnostic trajectory here.")
            else:
                for idx, h in enumerate(history, start=1):
                    pass_str = "✅ PASSED" if h.get("passed") else "⚠️ NEEDS WORK"
                    score_str = f"{h.get('score_percentage')}%"
                    date_str = str(h.get("completed_at", ""))[:16].replace("T", " ")
                    title = f"#{idx} | {h.get('role')} | Score: {score_str} ({pass_str}) — {date_str}"

                    with st.expander(title, expanded=(idx == 1)):
                        c1, c2, c3, c4 = st.columns(4)
                        c1.metric("Final Score", f"{h.get('score_percentage')}%")
                        c2.metric("Correct Answers", f"{h.get('correct_count')} / {h.get('total_questions')}")
                        c3.metric("Difficulty", h.get("difficulty", "Intermediate"))
                        c4.metric("Status", pass_str)

                        if h.get("summary_feedback"):
                            st.info(f"💡 **AI Summary:** {h.get('summary_feedback')}")

                        h_col_s, h_col_w = st.columns(2)
                        with h_col_s:
                            st.markdown("**Demonstrated Strengths:**")
                            for s in h.get("strengths", []):
                                st.markdown(f"- ✅ {s}")
                        with h_col_w:
                            st.markdown("**Identified Weaknesses:**")
                            for w in h.get("weaknesses", []):
                                st.markdown(f"- 🔴 {w}")

                        gaps = h.get("skill_gaps", [])
                        if gaps:
                            st.markdown("**Critical Skill Gaps vs JD:**")
                            for g in gaps:
                                st.markdown(f"- ⚠️ {g}")

                        plan = h.get("improvement_plan", [])
                        if plan:
                            st.markdown("**Personalized Improvement Plan:**")
                            for step in plan:
                                st.markdown(f"- {step}")

        except Exception as e:
            st.error(f"Failed to load history: {str(e)}")


def _render_mcq_form(selected_id: int, assessment: dict):
    """Renders the interactive MCQ assessment form."""
    questions = assessment.get("questions", [])
    if not questions:
        st.warning("This assessment has no questions.")
        return

    st.markdown("---")
    st.markdown("##### 📝 Please answer all questions below and submit for deterministic scoring:")

    with st.form(f"assessment_form_{selected_id}"):
        user_answers = {}
        for i, q in enumerate(questions):
            topic_badge = f"<span class='metric-badge badge-info'>{q.get('topic', 'General')}</span>"
            concept_badge = f"<span class='metric-badge badge-info'>Concept: {q.get('concept')}</span>" if q.get("concept") else ""
            skill_badge = f"<span class='metric-badge badge-warning'>{q.get('skill', '')}</span>"
            st.markdown(f"**Q{i+1}. {q.get('question')}** {skill_badge} {topic_badge} {concept_badge}", unsafe_allow_html=True)
            if q.get("why_the_question_is_relevant"):
                st.caption(f"💡 *Relevance to your profile & target JD:* {q.get('why_the_question_is_relevant')}")
            options = q.get("options", [])
            choice = st.radio(
                f"Select an answer for Q{i+1}:",
                options=options,
                key=f"q_{selected_id}_{q.get('id')}",
                index=None
            )
            if choice:
                user_answers[str(q.get("id"))] = choice
            st.write("")

        submitted = st.form_submit_button("Submit Assessment for Evaluation", type="primary", use_container_width=True)

    if submitted:
        total_q = len(questions)
        if len(user_answers) < total_q:
            st.warning(f"Please answer all {total_q} questions before submitting (currently answered {len(user_answers)}/{total_q}).")
        else:
            with st.spinner("Scoring answers deterministically & running Azure AI diagnostic evaluation..."):
                try:
                    result = api.submit_assessment(selected_id, user_answers)
                    st.success(f"Assessment Completed! Score: {result.get('score_percentage')}%")
                    st.rerun()
                except Exception as e:
                    st.error(f"Submission failed: {str(e)}")


def _display_assessment_result(result: dict):
    """Displays comprehensive AI performance diagnostics, deterministic score, and question review."""
    st.markdown("---")
    st.markdown("### 🏆 Assessment Results & AI Diagnostic Interpretation")

    score = result.get("score_percentage", 0.0)
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Final Score", f"{score}%")
    c2.metric("Correct Answers", f"{result.get('correct_count')} / {result.get('total_questions')}")
    c3.metric("Demonstrated Level", result.get("new_demonstrated_level", "Beginner"))
    c4.metric("Confidence Rating", result.get("new_confidence", "Medium"))

    if result.get("passed"):
        st.success(f"🎉 Pass: You demonstrated {result.get('new_demonstrated_level')} competency.")
    else:
        st.warning(f"Attention Needed: Your score of {score}% indicates key skill gaps requiring preparation.")

    per_skill = result.get("per_skill_scores") or {}
    if per_skill:
        st.markdown("#### 📊 Per-Skill Assessment Breakdown")
        st.caption("These scores directly persist into your **Skill Matrix** and calibrate your placement readiness.")
        sk_cols = st.columns(min(len(per_skill), 4))
        for idx, (sk_name, sk_score) in enumerate(per_skill.items()):
            col = sk_cols[idx % len(sk_cols)]
            with col:
                conf_label = "High" if sk_score >= 75.0 else ("Medium" if sk_score >= 50.0 else "Low")
                status_label = "Ready" if sk_score >= 75.0 else ("Needs Practice" if sk_score >= 50.0 else "Critical Gap")
                col.metric(label=sk_name, value=f"{sk_score}%")
                col.caption(f"Status: **{status_label}** ({conf_label})")

    summary_feedback = result.get("summary_feedback")
    if summary_feedback:
        st.info(f"💡 **AI Diagnostic Summary:** {summary_feedback}")

    col_s, col_w = st.columns(2)
    with col_s:
        st.markdown("#### 💪 Demonstrated Strengths")
        strengths = result.get("strengths") or []
        if strengths:
            for s in strengths:
                st.markdown(f"- ✅ **{s}**")
        else:
            st.info("No strong topics demonstrated in this session. Revisit foundational concepts.")

    with col_w:
        st.markdown("#### ⚠️ Identified Weaknesses")
        weaknesses = result.get("weaknesses") or []
        if weaknesses:
            for w in weaknesses:
                st.markdown(f"- 🔴 **{w}**")
        else:
            st.success("No weaknesses detected in this assessment!")

    col_gaps, col_topics = st.columns(2)
    with col_gaps:
        st.markdown("#### 🧩 Skill Gaps (Candidate vs JD)")
        skill_gaps = result.get("skill_gaps") or []
        if skill_gaps:
            for gap in skill_gaps:
                st.markdown(f"- ⚠️ **{gap}**")
        else:
            st.success("No unverified JD gaps detected!")

    with col_topics:
        st.markdown("#### 📚 Topics to Improve")
        topics = result.get("topics_to_improve") or []
        if topics:
            for t in topics:
                st.markdown(f"- 📖 **{t}**")
        else:
            st.write("All evaluated topics performed satisfactorily.")

    priorities = result.get("priority_areas") or []
    if priorities:
        st.markdown("#### 🔥 Priority Areas (Educational Prioritization)")
        for idx, p in enumerate(priorities, start=1):
            st.markdown(f"{idx}. **{p}** *(High impact for target role readiness)*")

    plan_steps = result.get("improvement_plan") or []
    if plan_steps:
        st.markdown("#### 📝 Personalized Improvement Plan")
        for step in plan_steps:
            st.markdown(f"- {step}")

    reassess = result.get("reassessment_recommendations")
    if reassess:
        st.markdown("#### 🔄 Reassessment Recommendation")
        st.markdown(f"> 🎯 **Guidance:** {reassess}")

    # Detailed Question Review (Grounding & Explanations)
    details = result.get("details") or []
    if details:
        st.markdown("---")
        st.markdown("#### 🔍 Detailed Question Review")
        for det in details:
            is_corr = det.get("is_correct")
            icon = "✅ Correct" if is_corr else "❌ Incorrect"
            q_title = f"{icon}: {det.get('question', '')[:85]}..."
            with st.expander(q_title, expanded=(not is_corr)):
                st.markdown(f"**Full Question:** {det.get('question')}")
                caption_items = []
                if det.get("skill"):
                    caption_items.append(f"Domain: **{det.get('skill')}**")
                if det.get("topic"):
                    caption_items.append(f"Topic: **{det.get('topic')}**")
                if det.get("concept"):
                    caption_items.append(f"Concept: **{det.get('concept')}**")
                if caption_items:
                    st.caption(" | ".join(caption_items))
                if det.get("why_the_question_is_relevant"):
                    st.caption(f"Why Relevant: {det.get('why_the_question_is_relevant')}")
                st.write(f"**Your Answer:** {det.get('selected_answer')}")
                st.write(f"**Correct Answer:** {det.get('correct_answer')}")
                st.info(f"**Explanation:** {det.get('explanation')}")
